version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080" 
    volumes:
      - ./src:/workspace/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_WEB_CORS_ALLOWED_ORIGINS=*
      - SPRING_WEB_CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS,PATCH
      - SPRING_WEB_CORS_ALLOWED_HEADERS=*
      - SPRING_WEB_CORS_ALLOW_CREDENTIALS=true
      - SPRING_WEB_CORS_EXPOSED_HEADERS=*
      - SPRING_HATEOAS_USE_HAL_AS_DEFAULT_JSON=true
      - SPRING_HATEOAS_ENABLE_HYPERMEDIA_SUPPORT=true
    restart: always
